In [4]:
import pandas as pd
import numpy as np

In [5]:
dates = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 4),
                  index=dates, columns=['A', 'B', 'C', 'D'])

In [6]:
df

                   A         B         C         D
2000-01-01  0.151833  0.029686 -0.003215  0.265743
2000-01-02  0.222714  0.350669  0.471751  1.418515
2000-01-03  0.841352  1.004938 -0.603018 -0.613067
2000-01-04  0.072127 -1.004486 -0.749719 -0.548796
2000-01-05  0.498446 -0.802449 -0.217770 -1.929711
2000-01-06 -0.196003  0.271155  0.061917  0.392487
2000-01-07 -0.108777 -0.570442 -1.525864 -0.083316
2000-01-08 -0.433396  0.074989 -0.391092 -0.321647

### ".loc"
With the `.loc[]` command you can provide the **names** of rows and columns, to access data. There are various combinations possible on how to do that:

1) Single entry for row and column
2) List of individual entries (can be put in either or both of the row and column locator)
3) Range from Start to End column/row name (this includes the actually defined end - different to index ranges!)

***See examples below!***

In [7]:
df.loc["2000-01-04", "B"]

np.float64(-1.004485645070809)

In [8]:
df.loc[["2000-01-01", "2000-01-04"], "B"]

2000-01-01    0.029686
2000-01-04   -1.004486
Name: B, dtype: float64

In [9]:
df.loc[["2000-01-01", "2000-01-04"], "B":"D"]

                   B         C         D
2000-01-01  0.029686 -0.003215  0.265743
2000-01-04 -1.004486 -0.749719 -0.548796

### ".iloc"
With the `.iloc[]` command you can provide the **indices** of rows and columns, to access data. There are various combinations possible on how to do that:

1) Single entry for row and column
2) All rows/columns using the `:` argument
3) List of individual entries (can be put in either or both of the row and column locator)
4) Range from Start to ***End+1*** column/row indices (this ***does NOT include the actually defined end*** - different to `.loc` ranges!)

***The examples below show the exact same output as before using the `.loc` command.***

In [15]:
df.iloc[3,1]

# you can see for yourself by comparing element-wise if the output is identical:
# df.loc["2000-01-04", "B"] == df.iloc[3,1]

np.float64(-1.004485645070809)

In [16]:
df.iloc[[0,3],1]
# df.loc[["2000-01-01", "2000-01-04"], "B"] == df.iloc[[0,3],1]

2000-01-01    0.029686
2000-01-04   -1.004486
Freq: 3D, Name: B, dtype: float64

In [17]:
df.iloc[[0,3],1:4]
# df.loc[["2000-01-01", "2000-01-04"], "B":"D"] == df.iloc[[0,3],1:4]

                   B         C         D
2000-01-01  0.029686 -0.003215  0.265743
2000-01-04 -1.004486 -0.749719 -0.548796